#!/usr/bin/env bash
# FaultWall setup script — downloads, configures, and starts the FaultWall proxy + monitor.
# Safe to run multiple times; exits early if already running.

set -euo pipefail

FAULTWALL_DIR="${HOME}/.faultwall"
FAULTWALL_BIN="${FAULTWALL_DIR}/faultwall"
POLICIES_FILE="${FAULTWALL_DIR}/policies.yaml"
PROXY_PORT=5433
MONITOR_PORT=8080
UPSTREAM="localhost:5432"
GITHUB_REPO="shreyasXV/faultwall"
LOG_DIR="${FAULTWALL_DIR}/logs"

# ── colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[faultwall]${NC} $*"; }
warn()  { echo -e "${YELLOW}[faultwall]${NC} $*"; }
error() { echo -e "${RED}[faultwall]${NC} $*" >&2; }

# ── helpers ───────────────────────────────────────────────────────────────────
port_in_use() { nc -z 127.0.0.1 "$1" 2>/dev/null; }

wait_for_port() {
  local port=$1 attempts=${2:-20} delay=${3:-0.5}
  for i in $(seq 1 "$attempts"); do
    port_in_use "$port" && return 0
    sleep "$delay"
  done
  return 1
}

# ── already running? ──────────────────────────────────────────────────────────
if port_in_use "$PROXY_PORT"; then
  info "FaultWall proxy already listening on port ${PROXY_PORT}. Nothing to do."
  exit 0
fi

# ── create dirs ───────────────────────────────────────────────────────────────
mkdir -p "${FAULTWALL_DIR}" "${LOG_DIR}"

# ── download binary if missing ────────────────────────────────────────────────
if [[ ! -x "${FAULTWALL_BIN}" ]]; then
  info "FaultWall binary not found — downloading latest release…"

  # Detect OS
  OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
  case "${OS}" in
    linux)  OS_TAG="linux"   ;;
    darwin) OS_TAG="darwin"  ;;
    *)      error "Unsupported OS: ${OS}"; exit 1 ;;
  esac

  # Detect architecture
  ARCH="$(uname -m)"
  case "${ARCH}" in
    x86_64|amd64)   ARCH_TAG="amd64"  ;;
    arm64|aarch64)  ARCH_TAG="arm64"  ;;
    *)              error "Unsupported architecture: ${ARCH}"; exit 1 ;;
  esac

  ASSET_NAME="faultwall_${OS_TAG}_${ARCH_TAG}"
  RELEASE_URL="https://github.com/${GITHUB_REPO}/releases/latest/download/${ASSET_NAME}"

  info "Downloading: ${RELEASE_URL}"
  if command -v curl &>/dev/null; then
    curl -fsSL --retry 3 -o "${FAULTWALL_BIN}" "${RELEASE_URL}"
  elif command -v wget &>/dev/null; then
    wget -q --tries=3 -O "${FAULTWALL_BIN}" "${RELEASE_URL}"
  else
    error "Neither curl nor wget found. Please install one and retry."
    exit 1
  fi

  chmod +x "${FAULTWALL_BIN}"
  info "Downloaded to ${FAULTWALL_BIN}"
else
  info "Found existing binary at ${FAULTWALL_BIN}"
fi

# Validate binary is executable
if ! "${FAULTWALL_BIN}" --version &>/dev/null && ! "${FAULTWALL_BIN}" version &>/dev/null; then
  warn "Binary may not be working correctly — proceeding anyway."
fi

# ── create default policies.yaml if missing ───────────────────────────────────
if [[ ! -f "${POLICIES_FILE}" ]]; then
  info "Creating default policies at ${POLICIES_FILE}…"
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  DEFAULT_POLICY="${SCRIPT_DIR}/default-policy.yaml"

  if [[ -f "${DEFAULT_POLICY}" ]]; then
    cp "${DEFAULT_POLICY}" "${POLICIES_FILE}"
    info "Copied default policy from ${DEFAULT_POLICY}"
  else
    # Inline fallback if the script is run standalone
    cat > "${POLICIES_FILE}" <<'YAML'
# FaultWall default policy — generated by setup.sh
# Edit this file and POST /api/policies/reload to apply changes.

default_policy: deny

agents:
  - id: openclaw-agent
    description: "Default OpenClaw agent — read-only access"
    token: "changeme"
    blocked_operations:
      - DROP
      - TRUNCATE
      - DELETE
      - ALTER
      - CREATE
    blocked_tables:
      - pg_catalog
      - users
      - payments
    allowed_operations:
      - SELECT
      - INSERT
      - UPDATE

blocked_functions:
  - pg_read_file
  - pg_write_file
  - pg_execute_server_program
  - pg_read_binary_file
  - lo_import
  - lo_export
  - dblink
  - copy_from
  - copy_to
YAML
    info "Created inline default policy"
  fi
fi

# ── start FaultWall proxy ─────────────────────────────────────────────────────
info "Starting FaultWall proxy on port ${PROXY_PORT} → upstream ${UPSTREAM}…"

nohup "${FAULTWALL_BIN}" \
  --proxy \
  --listen "0.0.0.0:${PROXY_PORT}" \
  --upstream "${UPSTREAM}" \
  --policies "${POLICIES_FILE}" \
  > "${LOG_DIR}/proxy.log" 2>&1 &

PROXY_PID=$!
echo "${PROXY_PID}" > "${FAULTWALL_DIR}/proxy.pid"
info "Proxy started (PID ${PROXY_PID})"

# ── start FaultWall monitor ───────────────────────────────────────────────────
if ! port_in_use "${MONITOR_PORT}"; then
  info "Starting FaultWall monitor/dashboard on port ${MONITOR_PORT}…"
  nohup "${FAULTWALL_BIN}" \
    > "${LOG_DIR}/monitor.log" 2>&1 &

  MONITOR_PID=$!
  echo "${MONITOR_PID}" > "${FAULTWALL_DIR}/monitor.pid"
  info "Monitor started (PID ${MONITOR_PID})"
else
  warn "Port ${MONITOR_PORT} already in use — skipping monitor start."
fi

# ── wait for proxy to be ready ────────────────────────────────────────────────
info "Waiting for proxy to accept connections on port ${PROXY_PORT}…"
if wait_for_port "${PROXY_PORT}" 30 0.5; then
  info "✓ FaultWall proxy is ready on port ${PROXY_PORT}"
else
  error "Proxy did not become ready within 15s. Check logs at ${LOG_DIR}/proxy.log"
  cat "${LOG_DIR}/proxy.log" 2>/dev/null | tail -20 || true
  exit 1
fi

# ── done ─────────────────────────────────────────────────────────────────────
echo ""
info "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
info "  FaultWall is running"
info "  Proxy  : localhost:${PROXY_PORT}  (→ ${UPSTREAM})"
info "  Monitor: http://localhost:${MONITOR_PORT}"
info "  Policies: ${POLICIES_FILE}"
info "  Logs   : ${LOG_DIR}/"
info "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
info "Connect via: psql \"host=localhost port=${PROXY_PORT} dbname=<db> application_name=agent:<id>:mission:<task>:token:<token>\""
