FROM python:3.12-slim
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*
COPY query-executor.py /app/query-executor.py
CMD ["python3", "/app/query-executor.py"]
